apply plugin: 'com.android.application'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

buildscript {
    dependencies {
    }

    repositories {
        jcenter()
        maven { url 'http://dl.bintray.com/iaguila/maven' }
    }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.cleverox.nuevopudahuel"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            resValue "string", "api_url", "http://54.191.135.153/flightsApi/v1"
            resValue "string", "banners_api_url", "http://54.191.135.153/bannersApi/v1"

            resValue "string", "moca_app_key", "KQNtJe6-SO-vRGdg3zAYgQ"
            resValue "string", "moca_app_secret", "3G31ZMiYxuQLXZLZoQjUcWkN88U="
        }
        debug {
            resValue "string", "api_url", "http://54.191.135.153/flightsApi/v1"
            resValue "string", "banners_api_url", "http://54.191.135.153/bannersApi/v1"

            resValue "string", "moca_app_key", "KQNtJe6-SO-vRGdg3zAYgQ"
            resValue "string", "moca_app_secret", "3G31ZMiYxuQLXZLZoQjUcWkN88U="
        }
    }
    signingConfigs {
        release {
            storeFile file('NuevoPudahuelKeystore.jks')
            storePassword 'pass4android'
            keyAlias 'nuevopudahuel'
            keyPassword 'pass4android'
        }
        debug {
            storeFile file('NuevoPudahuelKeystore.jks')
            storePassword 'pass4android'
            keyAlias 'nuevopudahuel'
            keyPassword 'pass4android'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:multidex:1.0.1'

    //UI
    compile 'com.android.support:appcompat-v7:24.0.0-alpha1'
    compile 'com.android.support:support-v4:24.0.0-alpha1'
    compile 'com.android.support:recyclerview-v7:24.0.0-alpha1'
    compile 'com.android.support:design:24.0.0-alpha1'
    compile 'uk.co.chrisjenx:calligraphy:2.1.0'

    //GOOGLE PLAY SERVICES
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-vision:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.google.android.gms:play-services-location:8.4.0'

    //Utils
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    compile 'net.moddity.bzutils.android:BZUtils-Android-Gradle:1.0.3@aar'

    //RETROFIT
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.google.code.gson:gson:2.4'

    //REALM
    compile 'io.realm:realm-android:0.87.4'
    
    //FACEBOOK
    compile 'com.facebook.android:facebook-android-sdk:4.+'

    //MOCA
    compile project(':moca-sdk-android-1.8.10')

    //TRACKING
    compile 'com.flurry.android:analytics:6.2.0'
}
