

buildscript {

    repositories {
        jcenter()
        maven { url 'http://dl.bintray.com/iaguila/maven' }
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'realm-android'
apply plugin: 'com.google.firebase.crashlytics'

android {

    compileSdkVersion 32
    buildToolsVersion '28.0.3'
    flavorDimensions "default"

    defaultConfig {
        applicationId "com.massiva.nuevopudahuel"
        minSdkVersion 19
        targetSdkVersion 32
        versionCode 129
        versionName "1.2.3"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            resValue "string", "api_url", "https://pudahuel2.gearlabs.cl/flightsApi/v1"
            resValue "string", "banners_api_url", "https://pudahuel2.gearlabs.cl/bannersApi/v1"

            //resValue "string", "api_url", "http://54.233.145.28/flightsApi/v1"
            //resValue "string", "banners_api_url", "http://54.233.145.28/bannersApi/v1"

            resValue "string", "moca_app_key", "30fG6xGjSqKoHPlRADloKw"
            resValue "string", "moca_app_secret", "BD2Hdenm8emN/9VRIcKn8RNGKSs="
        }
        debug {

            resValue "string", "api_url", "https://pudahuel2.gearlabs.cl/flightsApi/v1"
            resValue "string", "banners_api_url", "https://pudahuel2.gearlabs.cl/bannersApi/v1"

            //resValue "string", "api_url", "http://54.233.145.28/flightsApi/v1"
            //resValue "string", "banners_api_url", "http://54.233.145.28/bannersApi/v1"

//            MOCA PRO
            resValue "string", "moca_app_key", "30fG6xGjSqKoHPlRADloKw"
            resValue "string", "moca_app_secret", "BD2Hdenm8emN/9VRIcKn8RNGKSs="

//            MOCA TEST
//            resValue "string", "moca_app_key", "KQNtJe6-SO-vRGdg3zAYgQ"
//            resValue "string", "moca_app_secret", "3G31ZMiYxuQLXZLZoQjUcWkN88U="
        }
    }
    signingConfigs {
        release {
            storeFile file('NuevoPudahuelKeystore.jks')
            storePassword 'pass4android'
            keyAlias 'nuevopudahuel'
            keyPassword 'pass4android'
        }
        debug {
            storeFile file('NuevoPudahuelKeystore.jks')
            storePassword 'pass4android'
            keyAlias 'nuevopudahuel'
            keyPassword 'pass4android'
        }
    }
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    compileOptions {
        incremental true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dexOptions {
        preDexLibraries = false
        javaMaxHeapSize '4096m'
    }

    //PARA DESCARGA DE ZIPS, USADO EN MAPAS 2D ETC
    useLibrary 'org.apache.http.legacy'

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
    }

}



dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'

    implementation 'androidx.core:core:1.7.0'
    implementation 'androidx.lifecycle:lifecycle-runtime:2.4.1'

    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.emoji:emoji:1.1.0'
    implementation 'androidx.emoji2:emoji2:1.0.1'
    implementation 'androidx.emoji2:emoji2-views:1.0.1'
    implementation 'androidx.emoji2:emoji2-views-helper:1.0.1'
    implementation "androidx.startup:startup-runtime:1.1.1"

    //UI
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'uk.co.chrisjenx:calligraphy:2.1.0'

    //GOOGLE PLAY SERVICES
    //implementation 'com.google.android.gms:play-services-ads:20.5.0'
    implementation 'com.google.android.gms:play-services-vision:20.1.3'
    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'com.google.android.gms:play-services-location:19.0.1'


    //FIREBASE
    implementation platform('com.google.firebase:firebase-bom:29.1.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-messaging:23.0.0'
    implementation 'com.google.firebase:firebase-crashlytics-buildtools:2.8.1'

    //Utils
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    implementation 'net.moddity.bzutils.android:BZUtils-Android-Gradle:1.0.3@aar'

    //RETROFIT
    implementation 'com.squareup.retrofit:retrofit:1.9.0'
    implementation 'com.squareup.okhttp:okhttp:2.2.0'
    implementation 'com.google.code.gson:gson:2.8.0'

    //FACEBOOK
    implementation ('com.facebook.android:facebook-android-sdk:4.+'){
        exclude group: 'com.android.support', module:'support-v4'
        exclude group: 'com.android.support', module:'appcompat-v7'
    }


    //TRACKING
    implementation 'com.flurry.android:analytics:6.2.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

}
