

buildscript {

    repositories {
        jcenter()
        maven { url 'http://dl.bintray.com/iaguila/maven' }
    }
}

apply plugin: 'com.android.application'
apply plugin: 'realm-android'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
dexOptions {
javaMaxHeapSize "4g"
}
    compileSdkVersion 30
    buildToolsVersion '28.0.2'
    flavorDimensions "default"

    defaultConfig {
        applicationId "com.massiva.nuevopudahuel"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 129
        versionName "1.2.3"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            resValue "string", "api_url", "https://pudahuel2.gearlabs.cl/flightsApi/v1"
            resValue "string", "banners_api_url", "https://pudahuel2.gearlabs.cl/bannersApi/v1"

            //resValue "string", "api_url", "http://54.233.145.28/flightsApi/v1"
            //resValue "string", "banners_api_url", "http://54.233.145.28/bannersApi/v1"

            resValue "string", "moca_app_key", "30fG6xGjSqKoHPlRADloKw"
            resValue "string", "moca_app_secret", "BD2Hdenm8emN/9VRIcKn8RNGKSs="
        }
        debug {

            resValue "string", "api_url", "https://pudahuel2.gearlabs.cl/flightsApi/v1"
            resValue "string", "banners_api_url", "https://pudahuel2.gearlabs.cl/bannersApi/v1"

            //resValue "string", "api_url", "http://54.233.145.28/flightsApi/v1"
            //resValue "string", "banners_api_url", "http://54.233.145.28/bannersApi/v1"

//            MOCA PRO
            resValue "string", "moca_app_key", "30fG6xGjSqKoHPlRADloKw"
            resValue "string", "moca_app_secret", "BD2Hdenm8emN/9VRIcKn8RNGKSs="

//            MOCA TEST
//            resValue "string", "moca_app_key", "KQNtJe6-SO-vRGdg3zAYgQ"
//            resValue "string", "moca_app_secret", "3G31ZMiYxuQLXZLZoQjUcWkN88U="
        }
    }
    signingConfigs {
        release {
            storeFile file('NuevoPudahuelKeystore.jks')
            storePassword 'pass4android'
            keyAlias 'nuevopudahuel'
            keyPassword 'pass4android'
        }
        debug {
            storeFile file('NuevoPudahuelKeystore.jks')
            storePassword 'pass4android'
            keyAlias 'nuevopudahuel'
            keyPassword 'pass4android'
        }
    }
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    //PARA DESCARGA DE ZIPS, USADO EN MAPAS 2D ETC
    useLibrary 'org.apache.http.legacy'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:multidex:1.0.2'

    //UI
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:support-v4:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'uk.co.chrisjenx:calligraphy:2.1.0'

    //GOOGLE PLAY SERVICES
    implementation 'com.google.android.gms:play-services-ads:12.0.1'
    implementation 'com.google.android.gms:play-services-vision:12.0.1'
    implementation 'com.google.android.gms:play-services-gcm:12.0.1'
    implementation 'com.google.android.gms:play-services-location:12.0.1'


    //FIREBASE
    implementation 'com.google.firebase:firebase-core:12.0.1'
    implementation 'com.google.firebase:firebase-messaging:12.0.1'

    //Utils
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    implementation 'net.moddity.bzutils.android:BZUtils-Android-Gradle:1.0.3@aar'

    //RETROFIT
    implementation 'com.squareup.retrofit:retrofit:1.9.0'
    implementation 'com.squareup.okhttp:okhttp:2.2.0'
    implementation 'com.google.code.gson:gson:2.8.0'

    //FACEBOOK
    implementation ('com.facebook.android:facebook-android-sdk:4.+'){
        exclude group: 'com.android.support', module:'support-v4'
        exclude group: 'com.android.support', module:'appcompat-v7'
    }


    //TRACKING
    implementation 'com.flurry.android:analytics:6.2.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

apply plugin: 'com.google.gms.google-services'
